
logging:
  level:
    ROOT: INFO
    com.dazzle.asklepios: INFO

management:
  prometheus:
    metrics:
      export:
        enabled: false
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

services:
  asklepios-general-service-url: http://localhost:9090
  asklepios-setup-service-url: http://localhost:8082

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  liquibase:
    contexts: prod
    url: jdbc:postgresql://db-postgresql-nyc3-94186-do-user-10936078-0.j.db.ondigitalocean.com:25060/asklepios?sslmode=require
  mail:
    host: localhost
    port: 25
    username:
    password:
  r2dbc:
    url: r2dbc:postgresql://db-postgresql-nyc3-94186-do-user-10936078-0.j.db.ondigitalocean.com:25060/asklepios?sslmode=require
    username: asklepios
    password: AVNS_Dw0mJXT6mnivz3bN70_
  thymeleaf:
    cache: true
  cloud:
    gateway:
      default-filters:
        - JWTRelay
      routes:
        - id: reference-data
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/reference-data/**
          filters:
            - StripPrefix=0

        - id: appointment
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/appointment/**
          filters:
            - StripPrefix=0

        - id: attachment
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/attachment/**
          filters:
            - StripPrefix=0

        - id: dental
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/dental/**
          filters:
            - StripPrefix=0

        - id: dvm
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/dvm/**
          filters:
            - StripPrefix=0

        - id: encounter
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/encounter/**
          filters:
            - StripPrefix=0

        - id: general
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/general/**
          filters:
            - StripPrefix=0

        - id: lab
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/lab/**
          filters:
            - StripPrefix=0

        - id: medications
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/medications/**
          filters:
            - StripPrefix=0

        - id: observation
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/observation/**
          filters:
            - StripPrefix=0

        - id: pas
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/pas/**
          filters:
            - StripPrefix=0

        - id: rad
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/rad/**
          filters:
            - StripPrefix=0

        - id: setup
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/setup/**
          filters:
            - StripPrefix=0
        - id: newsetup
          uri: ${services.asklepios-setup-service-url}
          predicates:
            - Path=/api/setup/**
          filters:
            - StripPrefix=0
        - id: auth
          uri: ${services.asklepios-general-service-url}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

      httpclient:
        pool:
          max-connections: 1000

# ===================================================================
# To enable TLS in production, generate a certificate using:
# keytool -genkey -alias gateway -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# See details in topic "Create a Java Keystore (.JKS) from Let's Encrypt Certificates" on https://maximilian-boehm.com/en-gb/blog
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#   port: 443
#   ssl:
#     key-store: classpath:config/tls/keystore.p12
#     key-store-password: password
#     key-store-type: PKCS12
#     key-alias: selfsigned
#     # The ciphers suite enforce the security by deactivating some old and deprecated SSL cipher, this list was tested against SSL Labs (https://www.ssllabs.com/ssltest/)
#     ciphers: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 ,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA,TLS_RSA_WITH_CAMELLIA_128_CBC_SHA
# ===================================================================
server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024


asklepios:
  cors:
    allowed-origins: 'http://asklepios.nereuscloud.de,https://asklepios.nereuscloud.de'
    allowed-origin-patterns: 'https://*.asklepios.com'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${asklepios.clientApp.name}-alert,X-${asklepios.clientApp.name}-error,X-${asklepios.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: Y2RiNDRmMGM3ODZkM2FhMTEwYWYxZGE0NjQ3ODM5YThkYWFjZWYzMzY2ZDVkMTVhNGEyNDNmZTM0MzQ5NTRhMmVlMmFkNGVlODBmYTkyZWE4ZWYyMDRhZDJiZGU4YzJhMGEyN2U5NGUzMmNmNWU4Yzk2MDVkNzhmY2M3YTgyZDM=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:

      base-url: http://asklepios.nereuscloud.de/
      username: systemask73@gmail.com
      password: ocdh hvae hhsz cyxc

