spring:
  config:
    activate:
      on-profile: '!api-docs'
springdoc:
  api-docs:
    enabled: false
---
reactive:
  feign:
    circuit:
      breaker:
        enabled: true
  # client:
  #   config:
  #     default:
  #       connectTimeout: 5000
  #       readTimeout: 5000
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - gateway
          - health
          - info
          - logfile
          - loggers
          - prometheus
          - threaddump
          - liquibase
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60
  observations:
    key-values:
      application: ${spring.application.name}
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    data:
      repository:
        autotime:
          enabled: true
    tags:
      application: ${spring.application.name}

services:
  redirect-target-url: http://localhost:9090
#   redirect-target-url: http://67.207.78.195:8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - JWTRelay
      routes:
        - id: utility
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/utility/**
          filters:
            - StripPrefix=0

        - id: appointment
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/appointment/**
          filters:
            - StripPrefix=0

        - id: attachment
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/attachment/**
          filters:
            - StripPrefix=0

        - id: dental
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/dental/**
          filters:
            - StripPrefix=0

        - id: dvm
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/dvm/**
          filters:
            - StripPrefix=0

        - id: encounter
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/encounter/**
          filters:
            - StripPrefix=0

        - id: general
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/general/**
          filters:
            - StripPrefix=0

        - id: lab
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/lab/**
          filters:
            - StripPrefix=0

        - id: medications
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/medications/**
          filters:
            - StripPrefix=0

        - id: observation
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/observation/**
          filters:
            - StripPrefix=0

        - id: pas
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/pas/**
          filters:
            - StripPrefix=0

        - id: rad
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/rad/**
          filters:
            - StripPrefix=0

        - id: setup
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/setup/**
          filters:
            - StripPrefix=0

        - id: auth
          uri: ${services.redirect-target-url}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

      httpclient:
        pool:
          max-connections: 1000


  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by gradle when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: '@spring.profiles.active@'
    group:
      dev:
        - dev
        - api-docs
        # Uncomment to activate TLS for the dev profile
        #- tls
  jmx:
    enabled: false
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
  webflux:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          authority-prefix: ''
          authorities-claim-name: auth
  task:
    execution:
      thread-name-prefix: gateway-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: gateway-scheduling-
      pool:
        size: 2
  thymeleaf:
    mode: HTML
  output:
    ansi:
      console-available: true

server:
  servlet:
    session:
      cookie:
        http-only: true

springdoc:
  show-actuator: true

# Properties to be exposed on the /info management endpoint
info:
  # Comma separated list of profiles that will trigger the ribbon to show
  display-ribbon-on-profiles: 'dev'


asklepios:
  clientApp:
    name: 'gatewayApp'
#   By default CORS is disabled. Uncomment to enable.
  cors:
    allowed-origins: "http://localhost:8100,http://localhost:9000,http://localhost:3100"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count,X-${asklepios.clientApp.name}-alert,X-${asklepios.clientApp.name}-error,X-${asklepios.clientApp.name}-params"
    allow-credentials: true
    max-age: 1800
  mail:
    from: gateway@localhost
  api-docs:
    title: Asklepios API
    description: Asklepios API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name: Mohammad
    contact-url: Mohammad URL
    contact-email: mohammad.mattour@asklepios.com
    license: licensed
    license-url: www.asklepios.licence-url.com
    servers:
      - url: "https://asklepios.com/api"
        description: "Main server"
      - url: "https://backup.asklepios.com/api"
        description: "Backup server"
  security:
