---
# Service
apiVersion: v1
kind: Service
metadata:
    name: asklepios-api-gateway
    namespace: asklepios-sandbox
spec:
    type: ClusterIP
    selector:
        app: asklepios-api-gateway
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: asklepios-api-gateway
    namespace: asklepios-sandbox
spec:
    selector:
        matchLabels:
            app: asklepios-api-gateway
    replicas: 1
    template:
        metadata:
            labels:
                app: asklepios-api-gateway
        spec:
            containers:
                - name: asklepios-api-gateway
                  image: registry.digitalocean.com/asklepios/asklepios-api-gateway:d348c122fdc9feb0445db4489598974216efa6d5
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: spring.profiles.active
                      value: stage
                  ports:
                      - containerPort: 8080
                        name: asklepios-api
            imagePullSecrets:
                - name: asklepios

